version: "3"

services:
  app:
    build: .
    container_name: app_red48
    ports:
      - "8048:8080"
    restart: unless-stopped
    logging:
      driver: "json-file"
    networks:
      - demo-network

networks:
  demo-network:
    external: true
